### PR TITLE
Added isAjax function

### PR DESCRIPTION
**Pull request by Zroig**
Added isAjax function to the Request object in emeset-lite. Next the documentation of the function:

isAjax()

$request->isAjax(); //Returns true if controller has been called from an AJAX petition

### CODE REVIEW

**Comment by daniprados** [comment]
Great job on this contribution! Adding the ability to detect if a request is an AJAX call in the Request object of the Emeset framework is a valuable improvement. 

To proceed with accepting the pull request, please include documentation in the README.md that explains how this feature works, following the project's documentation conventions. This ensures that other contributors can easily understand and implement your addition. 

Thanks again for your work on this!

**Comment by Zroig** [comment]
It's done!

**Comment by daniprados** [comment]
This is a good improvement, but instead of writing the code of the function, provide an example of how to use the function.

**Comment by Zroig** [comment]
Updated readme with an example on how to use

**Comment by daniprados** [comment]
Pull request accepted!!!

**Pull request merged**
